name: 's4-scan-action'
description: 'Scan the repo when webhook is fired'
inputs:
    loginUrl:
        description: 'Request URL'
        required: true
    payloadUrl:
        description: 'Payload URL'
        required: true
    webhookSecret:
        description: 'Webhook secret'
        required: true
    method:
        description: 'Request Method'
        required: false
        default: 'POST'
    username:
        description: 'Auth Username'
        required: true
    password:
        description: 'Auth Password'
        required: true
outputs:
    response:
        description: 'HTTP Response Content'
runs:
    using: 'node12'
    main:  'src/index.js'

branding:
    icon: 'check'
    color: 'green'
